/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  darkMode: 'selector',
  theme: {
    extend: {
      fontFamily: {
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
      },
      spacing: {
        0: 'var(--space-0)',
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      colors: {
        // Backgrounds
        'bg-primary': 'var(--color-bg-primary)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'bg-tertiary': 'var(--color-bg-tertiary)',
        'bg-hover': 'var(--color-bg-hover)',
        'bg-active': 'var(--color-bg-active)',

        // Text
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-inverse': 'var(--color-text-inverse)',

        // Borders
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',

        // Accent
        accent: 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',
        'accent-light': 'var(--color-accent-light)',

        // Semantic
        success: 'var(--color-success)',
        'success-hover': 'var(--color-success-hover)',
        'success-light': 'var(--color-success-light)',
        'success-bg': 'var(--color-success-bg)',

        warning: 'var(--color-warning)',
        'warning-light': 'var(--color-warning-light)',
        'warning-bg': 'var(--color-warning-bg)',

        error: 'var(--color-error)',
        'error-hover': 'var(--color-error-hover)',
        'error-light': 'var(--color-error-light)',
        'error-bg': 'var(--color-error-bg)',

        info: 'var(--color-info)',
        'info-hover': 'var(--color-info-hover)',
        'info-light': 'var(--color-info-light)',
        'info-bg': 'var(--color-info-bg)',

        // Git status
        'git-modified': 'var(--color-git-modified)',
        'git-added': 'var(--color-git-added)',
        'git-deleted': 'var(--color-git-deleted)',
        'git-modified-bg': 'var(--color-git-modified-bg)',
        'git-added-bg': 'var(--color-git-added-bg)',
        'git-deleted-bg': 'var(--color-git-deleted-bg)',

        // Other
        highlight: 'var(--color-highlight)',
        selected: 'var(--color-selected)',
        'selected-hover': 'var(--color-selected-hover)',
        scrollbar: 'var(--color-scrollbar)',
        'scrollbar-hover': 'var(--color-scrollbar-hover)',
        'code-bg': 'var(--color-code-bg)',
        'pre-bg': 'var(--color-pre-bg)',
        'pre-text': 'var(--color-pre-text)',
        'tool-bg': 'var(--color-tool-bg)',
        'command-bg': 'var(--color-command-bg)',
        violet: 'var(--color-violet)',
        'violet-light': 'var(--color-violet-light)',
        'violet-bg': 'var(--color-violet-bg)',
        pink: 'var(--color-pink)',
        'pink-light': 'var(--color-pink-light)',
        'info-vivid': 'var(--color-info-vivid)',
        'mode-act': 'var(--color-mode-act)',
        'mode-plan': 'var(--color-mode-plan)',
        'mode-act-ring': 'var(--color-mode-act-ring)',
        'mode-plan-ring': 'var(--color-mode-plan-ring)',
        indigo: 'var(--color-indigo)',
        overlay: 'var(--color-overlay)',
        'inset-shadow': 'var(--color-inset-shadow)',
        'diff-divider': 'var(--color-diff-divider)',
        'diff-add-bg': 'var(--color-diff-add-bg)',
        'diff-add-text': 'var(--color-diff-add-text)',
        'diff-remove-bg': 'var(--color-diff-remove-bg)',
        'diff-remove-text': 'var(--color-diff-remove-text)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      transitionDuration: {
        fast: 'var(--transition-fast)',
        normal: 'var(--transition-normal)',
        slow: 'var(--transition-slow)',
      },
      transitionTimingFunction: {
        'ease-in': 'var(--ease-in)',
        'ease-out': 'var(--ease-out)',
        'ease-in-out': 'var(--ease-in-out)',
        'ease-spring': 'var(--ease-spring)',
      },
      zIndex: {
        hide: 'var(--z-hide)',
        base: 'var(--z-base)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        fixed: 'var(--z-fixed)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        tooltip: 'var(--z-tooltip)',
      },
      opacity: {
        0: 'var(--opacity-0)',
        5: 'var(--opacity-5)',
        10: 'var(--opacity-10)',
        15: 'var(--opacity-15)',
        20: 'var(--opacity-20)',
        25: 'var(--opacity-25)',
        30: 'var(--opacity-30)',
        35: 'var(--opacity-35)',
        40: 'var(--opacity-40)',
        45: 'var(--opacity-45)',
        50: 'var(--opacity-50)',
        55: 'var(--opacity-55)',
        60: 'var(--opacity-60)',
        65: 'var(--opacity-65)',
        70: 'var(--opacity-70)',
        75: 'var(--opacity-75)',
        80: 'var(--opacity-80)',
        85: 'var(--opacity-85)',
        90: 'var(--opacity-90)',
        95: 'var(--opacity-95)',
        100: 'var(--opacity-100)',
      },
      screens: {
        xs: 'var(--breakpoint-xs)',
        sm: 'var(--breakpoint-sm)',
        md: 'var(--breakpoint-md)',
        lg: 'var(--breakpoint-lg)',
        xl: 'var(--breakpoint-xl)',
        '2xl': 'var(--breakpoint-2xl)',
      },
      lineHeight: {
        tight: 'var(--leading-tight)',
        normal: 'var(--leading-normal)',
        relaxed: 'var(--leading-relaxed)',
      },
    },
  },
  plugins: [],
}
