"""Generate Markdown proof reports from scenario results and evidence.

Bead: bd-223o.16.4 (K4)

Implements the Showboat-style report builder: assembles a structured
Markdown document section-by-section from scenario run outcomes and
captured evidence artifacts.

Usage::

    report = build_proof_report(scenario_result, artifacts)
    Path('evidence/S-001/report.md').write_text(report)

Or use the builder for more control::

    builder = ProofReportBuilder('S-001', 'Login and Session')
    builder.add_summary(result)
    for step in result.step_results:
        builder.add_step_result(step, step_artifacts.get(step.step_number, []))
    builder.add_footer()
    report = builder.build()
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .scenario_runner import ScenarioResult, StepOutcome, StepResult
from .visual_proof import ArtifactType, EvidenceArtifact


_OUTCOME_ICONS = {
    StepOutcome.PASS: '\u2714',  # ✔
    StepOutcome.FAIL: '\u2718',  # ✘
    StepOutcome.SKIP: '\u23E9',  # ⏩
    StepOutcome.ERROR: '\u26A0',  # ⚠
}


class ProofReportBuilder:
    """Assemble a Markdown proof document section by section.

    The builder collects sections in order and produces a single
    Markdown string via :meth:`build`.
    """

    def __init__(self, scenario_id: str, title: str) -> None:
        self._scenario_id = scenario_id
        self._title = title
        self._sections: list[str] = []

    def add_header(
        self,
        *,
        started_at: str = '',
        finished_at: str = '',
        passed: bool | None = None,
    ) -> ProofReportBuilder:
        """Add the report header with scenario info."""
        verdict = ''
        if passed is True:
            verdict = ' \u2714 PASSED'
        elif passed is False:
            verdict = ' \u2718 FAILED'

        lines = [
            f'# {self._scenario_id}: {self._title}{verdict}',
            '',
        ]
        if started_at:
            lines.append(f'**Started:** {started_at}  ')
        if finished_at:
            lines.append(f'**Finished:** {finished_at}  ')
        if started_at or finished_at:
            lines.append('')

        self._sections.append('\n'.join(lines))
        return self

    def add_summary(self, result: ScenarioResult) -> ProofReportBuilder:
        """Add an aggregate summary table."""
        lines = [
            '## Summary',
            '',
            '| Metric | Value |',
            '|--------|-------|',
            f'| Total Steps | {result.total_steps} |',
            f'| Passed | {result.pass_count} |',
            f'| Failed | {result.fail_count} |',
            f'| Errors | {result.error_count} |',
            f'| Duration | {result.total_duration_ms:.0f}ms |',
            f'| Verdict | {"PASS" if result.passed else "FAIL"} |',
            '',
        ]
        self._sections.append('\n'.join(lines))
        return self

    def add_step_result(
        self,
        step: StepResult,
        artifacts: list[EvidenceArtifact] | None = None,
    ) -> ProofReportBuilder:
        """Add a single step with its evidence artifacts."""
        icon = _OUTCOME_ICONS.get(step.outcome, '?')
        lines = [
            f'### Step {step.step_number}: '
            f'{step.method} {step.path} {icon}',
            '',
            f'- **Expected:** {step.expected_status}',
            f'- **Actual:** {step.actual_status or "N/A"}',
            f'- **Outcome:** {step.outcome.value}',
            f'- **Duration:** {step.duration_ms:.0f}ms',
        ]

        if step.request_id:
            lines.append(f'- **Request ID:** `{step.request_id}`')

        if step.error_detail:
            lines.append(f'- **Error:** {step.error_detail}')

        if step.missing_fields:
            lines.append(
                f'- **Missing fields:** {", ".join(step.missing_fields)}'
            )

        # Attach evidence artifacts.
        if artifacts:
            lines.append('')
            lines.append('**Evidence:**')
            lines.append('')
            for artifact in artifacts:
                lines.append(_format_artifact(artifact))

        lines.append('')
        self._sections.append('\n'.join(lines))
        return self

    def add_footer(
        self,
        *,
        all_artifacts: list[EvidenceArtifact] | None = None,
    ) -> ProofReportBuilder:
        """Add the report footer with artifact index."""
        lines = ['---', '', '*Generated by boring-ui scenario runner (K4)*']

        if all_artifacts:
            lines.extend(['', '## Artifact Index', ''])
            lines.append('| # | Type | Step | File | Description |')
            lines.append('|---|------|------|------|-------------|')
            for i, artifact in enumerate(all_artifacts, 1):
                lines.append(
                    f'| {i} '
                    f'| {artifact.artifact_type.value} '
                    f'| {artifact.step_number} '
                    f'| `{artifact.file_path}` '
                    f'| {artifact.description} |'
                )
            lines.append('')

        self._sections.append('\n'.join(lines))
        return self

    def add_note(self, text: str) -> ProofReportBuilder:
        """Add a free-form note section."""
        self._sections.append(text + '\n')
        return self

    def build(self) -> str:
        """Return the assembled Markdown document."""
        return '\n'.join(self._sections)

    def write(self, path: Path) -> None:
        """Write the report to a file."""
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.build(), encoding='utf-8')


def build_proof_report(
    result: ScenarioResult,
    artifacts: tuple[EvidenceArtifact, ...] | list[EvidenceArtifact] = (),
) -> str:
    """Build a complete proof report from a scenario result and artifacts.

    Convenience function combining header, summary, step details, and
    artifact index into a single Markdown document.
    """
    artifact_list = list(artifacts)

    # Index artifacts by step number.
    by_step: dict[int, list[EvidenceArtifact]] = {}
    for a in artifact_list:
        by_step.setdefault(a.step_number, []).append(a)

    builder = ProofReportBuilder(result.scenario_id, result.title)
    builder.add_header(
        started_at=result.started_at,
        finished_at=result.finished_at,
        passed=result.passed,
    )
    builder.add_summary(result)

    for step in result.step_results:
        builder.add_step_result(step, by_step.get(step.step_number))

    builder.add_footer(all_artifacts=artifact_list)
    return builder.build()


# ── Helpers ────────────────────────────────────────────────────────


def _format_artifact(artifact: EvidenceArtifact) -> str:
    """Format an artifact as a Markdown bullet or image."""
    if artifact.artifact_type == ArtifactType.SCREENSHOT:
        return (
            f'  - ![{artifact.description}]({artifact.file_path})'
        )
    return (
        f'  - [{artifact.artifact_type.value}] '
        f'`{artifact.file_path}`: {artifact.description}'
    )
